# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDBInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Database name which is available to client', max_length=255, verbose_name='DB Name')),
                ('display_name', models.CharField(help_text='Enter a Database display name which is for lable', max_length=255, verbose_name='DB Display Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientdbinfo_createdby', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientdbinfo_updatedby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'ClientDBInfo',
                'verbose_name_plural': 'ClientDBInfos',
            },
        ),
    ]
