# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_clientdbinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdbinfo',
            name='color_back',
            field=models.CharField(blank=True, help_text='Ingresa el color caracteristico', max_length=7, null=True, verbose_name='Color de Fondo'),
        ),
    ]
