# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0004_auto_20160105_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdbinfo',
            name='color_back',
            field=models.CharField(default="rojo", help_text='Ingresa el color caracteristico', max_length=12, verbose_name='Color de Fondo'),
            preserve_default=False,
        ),
    ]
