# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['nombre_real'], 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'ordering': ['apellido1', 'apellido2', 'nombre1'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
    ]
